### ISSUE TITLE
Flatten attribute

### ISSUE THREAD

**Issue by kilork** [hd-gmbh-dev/raxb#21]
Similar to [#[serde(flatten)]](https://serde.rs/attr-flatten.html) we should have support for `flatten` attribute to allow to share common fields between multiple structures.

This allows also to implement extension types in XSD organically.

**Comment by jueseitz** [comment]
I cannot see how to implement this in the current way we're deserializing and serializing. For each field we basically enter a xml_deserialize function with a start tag and start a loop until the start event matches the end event. When to terminate on a flattened structure ?
